### PR TITLE
Add future annotations

### PR DESCRIPTION
**Pull request by Jonxslays**
#### Summary

This pull request adds future annotations in places where it can be used in the current code base.
It also restructures the imports from lightbulb.

#### Note
The lightbulb dependency has been updated to the github development branch, for the typing changes in tandemdude/hikari-lightbulb#176, until it is released to pypi.

### CODE REVIEW

**Review by parafoxia — CHANGES_REQUESTED** [review]
Looks good so far. https://github.com/tandemdude/hikari-lightbulb/commit/b97c183da3ab72e19afd0e758accb4196d9221de has been released since you made these initial changes, so you can replace `lightbulb.Context` with `lightbulb.SlashContext` now, as prefix contexts will never be needed.

**Review by parafoxia — APPROVED** [review]
Obvs when 2.0.4 releases to stable that can be updated and this merged, but for now this is blocked until then. Everything here looks good though.

**Comment by Jonxslays** [comment]
I mean this pr has the development branch targeted for lightbulb, it could technically be merged now and that dependency updated to 2.0.4 when it releases.

**Comment by parafoxia** [comment]
This *is* true, yeah. I'd rather not accidently introduce anything down the line between now and then, so may be best to lock to commit until it's released?

**Comment by Jonxslays** [comment]
Fair. I'll be starting the feeds cog from this commit.

**Comment by parafoxia** [comment]
Ah fuck it, I'm just gonna merge now. I'll update it when I do #135.

**Pull request merged**
