### PR TITLE
Db.py updates

### PR DESCRIPTION
**Pull request by IkBenOlie5**
#85

### CODE REVIEW

**Review by mshaugh — CHANGES_REQUESTED** [review]
Clean up the commit history.

**Comment by IkBenOlie5** [comment]
how?

**Comment by parafoxia** [comment]
Don't worry about it. If it looks fine we'll just squash them into one. That's what I've been doing for all the recent PRs tbh.

**Comment by IkBenOlie5** [comment]
ok!

**Review by parafoxia — APPROVED** [review]

**Comment by IkBenOlie5** [comment]
i mean jon gave me that guide so i squashed them

**Comment by Jonxslays** [comment]
> but that dismissed the review...

it is a setting in the repository. it automatically happens when that box is checked.

**Review by parafoxia — APPROVED** [review]
Stop commenting on it 😆

**Pull request merged**
