### PR TITLE
use aiofiles for executescript

### PR DESCRIPTION
**Pull request by IkBenOlie5**
Very small pr, just change from normal opening to aiofiles opening.

### CODE REVIEW

**Comment by parafoxia** [comment]
We typically don't accept PRs without a corresponding issue. Please create a new issue for this.

**Review by parafoxia — APPROVED** [review]

**Comment by IkBenOlie5** [comment]
#86 done :)

**Comment by parafoxia** [comment]
Cheers! What's your name on Discord btw? Just so I can give you credit for it.

**Comment by IkBenOlie5** [comment]
I'm farquaad :)

**Comment by parafoxia** [comment]
Aaaaah yes, I see. I thought the Olie part was familiar but I couldn't place it lmao.

**Comment by IkBenOlie5** [comment]
oh oops
didnt mean to do that here too

**Comment by IkBenOlie5** [comment]
fricking git going russian

**Comment by IkBenOlie5** [comment]
how do i remove the last 2 commits?

**Comment by IkBenOlie5** [comment]
i cant remove them, my git is all fricked up and in russian. they dont show up on my git log neither

**Comment by parafoxia** [comment]
```
git reset --soft HEAD~2
git restore --staged .
```

**Comment by IkBenOlie5** [comment]
doesnt work, ill just create a new pr. easier than fixing this lmao

**Comment by parafoxia** [comment]
Superceded by #91.

**Pull request closed without merging**
